module.exports = {
  ROLES: {
    SUPER_ADMIN: 'SUPER_ADMIN',
    ADMIN: 'ADMIN',
    OPERATIONAL: 'OPERATIONAL',
    DATA_ANALYST: 'DATA_ANALYST',
    VOLUNTEER: 'VOLUNTEER',
    PUBLIC_USER: 'PUBLIC_USER'
  },
  VOLUNTEER_STATUS: {
    PENDING: 'PENDING',
    UNDER_REVIEW: 'UNDER_REVIEW',
    APPROVED: 'APPROVED',
    ACTIVE: 'ACTIVE',
    INACTIVE: 'INACTIVE',
    SUSPENDED: 'SUSPENDED',
    REJECTED: 'REJECTED'
  },
  CAMPAIGN_TYPES: [
    'POLIO',
    'MALARIA',
    'MATERNAL_HEALTH',
    'CHILD_HEALTH',
    'NUTRITION',
    'IMMUNIZATION',
    'DISEASE_AWARENESS',
    'HYGIENE',
    'TB',
    'COVID_RESPIRATORY',
    'EMERGENCY_RESPONSE',
    'OTHER'
  ],
  CAMPAIGN_STATUS: {
    DRAFT: 'DRAFT',
    PLANNED: 'PLANNED',
    ACTIVE: 'ACTIVE',
    PAUSED: 'PAUSED',
    COMPLETED: 'COMPLETED',
    CANCELLED: 'CANCELLED'
  },
  TASK_STATUS: {
    ASSIGNED: 'ASSIGNED',
    ACCEPTED: 'ACCEPTED',
    REJECTED: 'REJECTED',
    IN_PROGRESS: 'IN_PROGRESS',
    SUBMITTED: 'SUBMITTED',
    UNDER_REVIEW: 'UNDER_REVIEW',
    APPROVED: 'APPROVED',
    COMPLETED: 'COMPLETED',
    CANCELLED: 'CANCELLED'
  },
  TASK_PRIORITY: {
    LOW: 'LOW',
    MEDIUM: 'MEDIUM',
    HIGH: 'HIGH',
    URGENT: 'URGENT'
  },
  FIELD_SUBMISSION_STATUS: {
    PENDING: 'PENDING',
    APPROVED: 'APPROVED',
    REJECTED: 'REJECTED',
    FLAGGED: 'FLAGGED'
  },
  INVENTORY_TRANSACTION_TYPES: {
    STOCK_IN: 'STOCK_IN',
    STOCK_OUT: 'STOCK_OUT',
    TRANSFER: 'TRANSFER',
    ADJUSTMENT: 'ADJUSTMENT',
    VOLUNTEER_ISSUE: 'VOLUNTEER_ISSUE',
    RETURN: 'RETURN',
    DAMAGED_EXPIRED: 'DAMAGED_EXPIRED'
  },
  SUPPLY_REQUEST_STATUS: {
    REQUESTED: 'REQUESTED',
    UNDER_REVIEW: 'UNDER_REVIEW',
    APPROVED: 'APPROVED',
    ISSUED: 'ISSUED',
    RECEIVED: 'RECEIVED',
    REJECTED: 'REJECTED',
    CANCELLED: 'CANCELLED'
  },
  EMERGENCY_SEVERITY: {
    LOW: 'LOW',
    MEDIUM: 'MEDIUM',
    HIGH: 'HIGH',
    CRITICAL: 'CRITICAL'
  },
  NOTIFICATION_TYPES: {
    TASK_ASSIGNED: 'TASK_ASSIGNED',
    TASK_REMINDER: 'TASK_REMINDER',
    TASK_UPDATE: 'TASK_UPDATE',
    CAMPAIGN_ANNOUNCEMENT: 'CAMPAIGN_ANNOUNCEMENT',
    TRAINING_ASSIGNED: 'TRAINING_ASSIGNED',
    LOW_INVENTORY: 'LOW_INVENTORY',
    REPORT_STATUS: 'REPORT_STATUS',
    EMERGENCY_ALERT: 'EMERGENCY_ALERT',
    SYSTEM: 'SYSTEM'
  }
};
